# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # test
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: check python files
        uses: cclauss/Find-Python-syntax-errors-action@master

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script to zip all functions
        run: |
          zip -j printhello.zip ./functions/printhello/*.py
          zip -ur printhello.zip psycopg2
      - name: deploy to aws printhello
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: printhello
          zip_file: printhello.zip
          handler: lambda_function.lambda_handler
          aws_region: eu-central-1
          role: arn:aws:iam::938690581919:role/service-role/db_data-role-67ja8s4y
          runtime: python3.6

  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # test
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script to zip all functions
        run: |
          zip -j printhello2.zip ./functions/printhello2/*.py
          zip -ur printhello2.zip psycopg2
          zip -j printpalme240.zip ./functions/printpalme240/*.py
          zip -ur printpalme240.zip psycopg2
      - name: deploy to aws printhello2
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: printhello2
          zip_file: printhello2.zip
          handler: lambda_function.lambda_handler
          aws_region: eu-central-1
          role: arn:aws:iam::938690581919:role/service-role/db_data-role-67ja8s4y
          runtime: python3.6
      - name: deploy to aws printhello2
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: printpalme240
          zip_file: printpalme240.zip
          handler: lambda_function.lambda_handler
          aws_region: eu-central-1
          role: arn:aws:iam::938690581919:role/service-role/db_data-role-67ja8s4y
          runtime: python3.6          
